version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgresdb
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - data:/data
volumes:
  data: {}