version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysqldb
    env_file: ./.env
    environment:
      MYSQLDB_USER: $MYSQLDB_USER
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    volumes:
      - data:/data
  mongodb:
    image: mongo
    container_name: mongodb
    env_file: ./.env
    ports:
        - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
        - data:/data
  mongo-express:
    image: mongo-express
    env_file: ./.env
    container_name: mongo-express
    restart: always
    ports:
        - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: $ME_CONFIG_MONGODB_ADMINUSERNAME
        ME_CONFIG_MONGODB_ADMINPASSWORD: $ME_CONFIG_MONGODB_ADMINPASSWORD
        ME_CONFIG_MONGODB_SERVER: $ME_CONFIG_MONGODB_SERVER
volumes:
    data: {}
networks:
    default:
        name: mongodb_network