version: '3.8'

services:
  localstack:
    image: localstack/localstack:0.14.2
    container_name: localstack
    ports:
      - '4566:4566'
    environment:
      - DEFAULT_REGION=eu-central-1
      - SERVICES=sqs
      - INFO=1